#  4.2 Exercise: Sentiment Analysis

Name : Ragunath Gunasekaran


In [98]:
  # Importing Libraries  
    
import pandas as pd
import unicodedata
import sys
import numpy as np

from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import CountVectorizer

## Step 1 - Load the data file DailyComments.csv from the Week 4 Data Files into a data frame.

1.  Loading the data

2.  Text Cleaning or Preprocessing

            Remove Punctuations, Numbers
            Stemming
            Convert each word into its lower case


In [99]:
# Assign File Location 
FileLocation='DailyComments.csv'
# Loading the data from .csv to Dataframe through Pandas Library
Comments_df = pd.read_csv(FileLocation)
print(Comments_df)
# Comments field
Comments = Comments_df['comments']
Comments_df.head()

  Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!


Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.

In [100]:
# converting into the lowercase
Comments=Comments.apply(lambda x: x.lower())
Comments

0                               hello, how are you?
1                              today is a good day!
2    it's my birthday so it's a really special day!
3         today is neither a good day or a bad day!
4                             i'm having a bad day.
5         there' s nothing special happening today.
6                        today is a super good day!
Name: comments, dtype: object

In [101]:
punctuation = dict.fromkeys(i for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P'))
# removing puncutation
Comments= [string.translate(punctuation) for string in Comments]
Comments

['hello how are you',
 'today is a good day',
 'its my birthday so its a really special day',
 'today is neither a good day or a bad day',
 'im having a bad day',
 'there s nothing special happening today',
 'today is a super good day']

In [102]:
# PorterStemmer
ps = PorterStemmer()

# Applying NLTK’s PorterStemmer
Comments_df['comments'] = Comments_df['comments'].apply(lambda word_list: [ ps.stem(word) for word in word_list])

###  Loaded the data from daily comment CSV File to dataframe

## Step 2 - Identify a scheme to categorize each comment as positive or negative. 

Positive  - Comments with Positive words Like Happy, Good, Super, Excellent.

Negative  - Comments with Positive words Like Bad, Angry, Worst.

Netural  -  Both Positive or Negative.


In [103]:
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(Comments)
print("")
print("vectorized words")
print("")
print(vectorizer.get_feature_names())
print("")
print("Identify Feature Words - Matrix View")
print("")
print( X.toarray())

df = pd.DataFrame({'text' : Comments})


vectorized words

['bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'im', 'really', 'special', 'super', 'today']

Identify Feature Words - Matrix View

[[0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 1]
 [0 1 1 0 0 0 0 0 1 1 0 0]
 [1 0 2 1 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 1]
 [0 0 1 1 0 0 0 0 0 0 1 1]]


##  Implement your sentiment analysis with code and display the results

In [104]:
#check for positive words and negative words

df['positive1'] = df.text.str.count('good')|df.text.str.count('happy')|df.text.str.count('super')|df.text.str.count('excellent')
df['positive2']= df.text.str.count('special')|df.text.str.count('nice')

df['negative'] = df.text.str.count('bad')|df.text.str.count('worst')|df.text.str.count('angry')

df['netural'] = df.text.str.count('good') & df.text.str.count('bad')

df['TotalScore'] = df.positive1 + df.positive2 - df.negative

print(" The Final Results are as below")
print(df)


# Display Results
Z = sum(df['TotalScore'])
print("")
print("Overall Score:  ",Z)

 The Final Results are as below
                                          text  positive1  positive2  \
0                            hello how are you          0          0   
1                          today is a good day          1          0   
2  its my birthday so its a really special day          0          1   
3     today is neither a good day or a bad day          1          0   
4                          im having a bad day          0          0   
5      there s nothing special happening today          0          1   
6                    today is a super good day          1          0   

   negative  netural  TotalScore  
0         0        0           0  
1         0        0           1  
2         0        0           1  
3         1        1           0  
4         1        0          -1  
5         0        0           1  
6         0        0           1  

Overall Score:   3


## Conclusion

1. Data get loaded into Data Frame

2. Preprocessing the data for Text Analytics

3. Applied logics for Sentiment Analysis for comments

4. Displayed the results of the outcome