# Exercise 1.2 - Working with Arrays

## Loading Libraries

In [166]:
import numpy as np
import pandas as pd

from numpy import array
from numpy import random

###  smaller array

In [167]:
SmallerArray = random.choice(random.randint(1,500), size=(3, 2))
print(SmallerArray)

[[104  27]
 [ 14  22]
 [100 230]]


In [168]:
print("Sum of all elements:")
print(np.sum(SmallerArray))
print("Sum of each column:")
print(np.sum(SmallerArray, axis=0))
print("Sum of each row:")
print(np.sum(SmallerArray, axis=1))

Sum of all elements:
497
Sum of each column:
[218 279]
Sum of each row:
[131  36 330]


In [169]:
print("Min of all elements:")
print(np.min(SmallerArray))
print("Max of all elements:")
print(np.max(SmallerArray))
print("average of all elements:")
print(np.average(SmallerArray))
print("mean of all elements:")
print(np.mean(SmallerArray))
print("std of all elements:")
print(np.std(SmallerArray))

Min of all elements:
14
Max of all elements:
230
average of all elements:
82.83333333333333
mean of all elements:
82.83333333333333
std of all elements:
75.22946379060683


In [176]:
SmallerArray_df = pd.DataFrame(data = SmallerArray) 
SmallerArray_df.columns=["Col "+ str(i+1) for i in range(0, 2)]
SmallerArray_df.index =["index "+ str(i+1) for i in range(0, 3)]
SmallerArray_df

Col 1  Col 2
index 1    104     27
index 2     14     22
index 3    100    230

## 1. Create an array of size [10,50] and use the random function to fill it with integers between 1 and 500 (inclusive). Load it to a DataFrame.

In [171]:
#  choice()  returns a randomly selected element from the specified sequence
#  randint() returns an integer number selected element from the specified range 1 to 500

ArrayAll = random.choice(random.randint(2,500), size=(10, 50))
print(ArrayAll)

[[114  73 197  39 219  27 142 180  98 139 217 110 168 161 157  78 202 242
  156 174 242 211 150 138 159 152  22 177  43 144 165 139 247 247 107   0
   52 243 231 220 157  79  79 119 228  37  37 195  98  40]
 [ 23  94 112  31 146 221  26  24  83 243 204  74 197 241  12 167 236 247
   87   8 100  13 119   0 224 153 177  67 122  26  23 174 156  71 110 139
  112 142  47 250  51 164   3 208 160  49 125 195 119  93]
 [ 30 170 208 108 199   0 118  96  65  31 152 238 210  69  88 170  36 155
  146  15 210 162  90  54 116 160 174 211  95  14 210  73 130 201 103  32
  217  22 227 159  37 238 183 219 146  99 213 123 237 155]
 [121 103  83  22 174 194  62  83 150  84   2  34 225 151 229   9  65 108
  117 140 138 165   6 205 142 133 169  27 204  39 215 242 190 155 107   0
  221  29 131  76 153  54 109 189  65  84 190 217  89 102]
 [  6 253 118 159  87 131 127 119 109 166 224  87 158 185 187  72   8  94
  186 241 246 220 142  75 110 109  57 210  33 149  67  46 151  34  43 184
   32 248  17  62  94  8

## 2. Calculate the sum of each row; the sum of each column; and the sum of all entries.

In [172]:
print("Sum of all elements:")
print(np.sum(ArrayAll))
print("Sum of each column:")
print(np.sum(ArrayAll, axis=0))
print("Sum of each row:")
print(np.sum(ArrayAll, axis=1))

Sum of all elements:
62994
Sum of each column:
[ 653 1365 1366  888 1249 1073  851 1195 1291 1505 1547 1103 1494 1204
 1137  791 1374 1735 1411 1343 1412 1363 1226  978 1319 1400 1160 1400
 1239  901 1709 1440 1545 1113  983  887 1044 1232 1216 1558 1119 1162
 1377 1644 1599 1023 1613 1283 1388 1086]
Sum of each row:
[7051 5868 6614 6002 6121 6716 5972 6009 6185 6456]


## 3. Determine the minimum; maximum; average; and standard deviation of all entries.

In [173]:
print("Min of all elements:")
print(np.min(ArrayAll))
print("Max of all elements:")
print(np.max(ArrayAll))
print("average of all elements:")
print(np.average(ArrayAll))
print("mean of all elements:")
print(np.mean(ArrayAll))
print("std of all elements:")
print(np.std(ArrayAll))

Min of all elements:
0
Max of all elements:
253
average of all elements:
125.988
mean of all elements:
125.988
std of all elements:
72.14934411344291


## 4. Sort the DataFrame: a) sort on column 2; b) sort on row 2.

In [177]:
array_df = pd.DataFrame(data = ArrayAll) 

In [178]:
array_df.columns=["Col "+ str(i+1) for i in range(0, 50)]
array_df.index =["index "+ str(i+1) for i in range(0, 10)]
array_df

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  \
index 1     114     73    197     39    219     27    142    180     98   
index 2      23     94    112     31    146    221     26     24     83   
index 3      30    170    208    108    199      0    118     96     65   
index 4     121    103     83     22    174    194     62     83    150   
index 5       6    253    118    159     87    131    127    119    109   
index 6      35    156     90    176     45    141     73    240    131   
index 7     142     45    248     49     25     29     40     34     12   
index 8      21    207     37    106    176    221     39    119    242   
index 9      98     35    178    129    153     86    208     60    149   
index 10     63    229     95     69     25     23     16    240    252   

          Col 10  ...  Col 41  Col 42  Col 43  Col 44  Col 45  Col 46  Col 47  \
index 1      139  ...     157      79      79     119     228      37      37   
index 2      243  ...      51     164       3     208     160      49     125   
index 3       31  ...      37     238     183     219     146      99     213   
index 4       84  ...     153      54     109     189      65      84     190   
index 5      166  ...      94      84     216      71     192     167     192   
index 6      136  ...     136      86     247     203     198      25     235   
index 7      222  ...     188      41     204     130      40      67     155   
index 8      199  ...      83      77     190     211     226      97     219   
index 9      120  ...     185     154     128     186     108     164      18   
index 10     165  ...      35     185      18     108     236     234     229   

          Col 48  Col 49  Col 50  
index 1      195      98      40  
index 2      195     119      93  
index 3      123     237     155  
index 4      217      89     102  
index 5      148       2       3  
index 6       75     239     228  
index 7       67      93     179  
index 8      166     140      11  
index 9       95     143      69  
index 10       2     228     206  

[10 rows x 50 columns]

In [179]:
array_df.sort_values(by=['Col 2'])

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  \
index 9      98     35    178    129    153     86    208     60    149   
index 7     142     45    248     49     25     29     40     34     12   
index 1     114     73    197     39    219     27    142    180     98   
index 2      23     94    112     31    146    221     26     24     83   
index 4     121    103     83     22    174    194     62     83    150   
index 6      35    156     90    176     45    141     73    240    131   
index 3      30    170    208    108    199      0    118     96     65   
index 8      21    207     37    106    176    221     39    119    242   
index 10     63    229     95     69     25     23     16    240    252   
index 5       6    253    118    159     87    131    127    119    109   

          Col 10  ...  Col 41  Col 42  Col 43  Col 44  Col 45  Col 46  Col 47  \
index 9      120  ...     185     154     128     186     108     164      18   
index 7      222  ...     188      41     204     130      40      67     155   
index 1      139  ...     157      79      79     119     228      37      37   
index 2      243  ...      51     164       3     208     160      49     125   
index 4       84  ...     153      54     109     189      65      84     190   
index 6      136  ...     136      86     247     203     198      25     235   
index 3       31  ...      37     238     183     219     146      99     213   
index 8      199  ...      83      77     190     211     226      97     219   
index 10     165  ...      35     185      18     108     236     234     229   
index 5      166  ...      94      84     216      71     192     167     192   

          Col 48  Col 49  Col 50  
index 9       95     143      69  
index 7       67      93     179  
index 1      195      98      40  
index 2      195     119      93  
index 4      217      89     102  
index 6       75     239     228  
index 3      123     237     155  
index 8      166     140      11  
index 10       2     228     206  
index 5      148       2       3  

[10 rows x 50 columns]

In [180]:
array_df.sort_index()

Col 1  Col 2  Col 3  Col 4  Col 5  Col 6  Col 7  Col 8  Col 9  \
index 1     114     73    197     39    219     27    142    180     98   
index 10     63    229     95     69     25     23     16    240    252   
index 2      23     94    112     31    146    221     26     24     83   
index 3      30    170    208    108    199      0    118     96     65   
index 4     121    103     83     22    174    194     62     83    150   
index 5       6    253    118    159     87    131    127    119    109   
index 6      35    156     90    176     45    141     73    240    131   
index 7     142     45    248     49     25     29     40     34     12   
index 8      21    207     37    106    176    221     39    119    242   
index 9      98     35    178    129    153     86    208     60    149   

          Col 10  ...  Col 41  Col 42  Col 43  Col 44  Col 45  Col 46  Col 47  \
index 1      139  ...     157      79      79     119     228      37      37   
index 10     165  ...      35     185      18     108     236     234     229   
index 2      243  ...      51     164       3     208     160      49     125   
index 3       31  ...      37     238     183     219     146      99     213   
index 4       84  ...     153      54     109     189      65      84     190   
index 5      166  ...      94      84     216      71     192     167     192   
index 6      136  ...     136      86     247     203     198      25     235   
index 7      222  ...     188      41     204     130      40      67     155   
index 8      199  ...      83      77     190     211     226      97     219   
index 9      120  ...     185     154     128     186     108     164      18   

          Col 48  Col 49  Col 50  
index 1      195      98      40  
index 10       2     228     206  
index 2      195     119      93  
index 3      123     237     155  
index 4      217      89     102  
index 5      148       2       3  
index 6       75     239     228  
index 7       67      93     179  
index 8      166     140      11  
index 9       95     143      69  

[10 rows x 50 columns]